apiVersion: apps/v1
kind: Deployment
metadata: { name: reactapp }
spec:
  replicas: 2
  selector: { matchLabels: { app: reactapp } }
  template:
    metadata: { labels: { app: reactapp } }
    spec:
      containers:
        - name: reactapp
          image: <YOUR_ECR_REPO>:latest
          ports: [{containerPort: 80}]

